### PR TITLE
Update IPythonMagics commands

### PR DESCRIPTION
**Pull request by a-larkins99**
Have adjusted the IPythonMagics commands used within `demo.ipynb` to replace the old, and now removed, Pace-Python commands with those provided by [libpymcr](https://github.com/pace-neutrons/libpymcr).  Resolves issue #1. 

`%pace` and `%pace-python` commands have been changed to use `%matlab_plot_mode`

### CODE REVIEW

**Comment by a-larkins99** [comment]
Prior to merging, the line `By default the `'inline'` option is used with a 400x300@150 dpi figure. We will change that to 100 dpi:` in `demo.ipynb` needs checking. If I have understood libpymcrs IPythonMagics help output it is 100 dpi by default and as such this example should be changed to something else.

**Review by mducle — APPROVED** [review]
Looks good so far - were you planning to add anything else (the PR is in draft mode)?

**Comment by a-larkins99** [comment]
If you could just checkout what I mentioned in the comment and let me know if this needs changing then I can make any necessary edit and change to non draft

**Comment by mducle** [comment]
> Prior to merging, the line `By default the `'inline'` option is used with a 400x300@150 dpi figure. We will change that to 100 dpi:` in `demo.ipynb` needs checking. If I have understood libpymcrs IPythonMagics help output it is 100 dpi by default and as such this example should be changed to something else.

Yes, you're right, the new default is [indeed 100dpi](https://github.com/pace-neutrons/libpymcr/blob/main/libpymcr/IPythonMagics.py#L155), so yeah, you can swap it around to "... default ... is ... a 400x300@100 dpi figure. We will change that to 150 dpi:".

**Pull request merged**
